import { apiRequest } from "./client";
import type { CreateKitInput, KitRecord, JDExtractionResult, GeneratedQuestion, CoverageResult, Flashcard, Schedule } from "@/types/api";

export const listKits = () => apiRequest<{ kits: KitRecord[] }>("/api/kits");
export const getKit = (id: string) => apiRequest<{ kit: KitRecord }>(`/api/kits/${id}`);
export const createKit = (input: CreateKitInput) => apiRequest<{ kit: KitRecord }>("/api/kits", { method: "POST", body: input });
export const deleteKit = (id: string) => apiRequest<{ success: boolean }>(`/api/kits/${id}`, { method: "DELETE" });
export const researchInterview = (id: string) => apiRequest<{ research: NonNullable<KitRecord["research"]>["interview"] }>(`/api/kits/${id}/research/interview`, { method: "POST" });
export const extractKit = (id: string) => apiRequest<{ extraction: JDExtractionResult }>(`/api/kits/${id}/extract`, { method: "POST" });
export const generateQuestions = (id: string) => apiRequest<{ questions: GeneratedQuestion[]; warnings: { code: string; message: string }[]; coverage: CoverageResult }>(`/api/kits/${id}/generate/questions`, { method: "POST" });
export const generateFlashcards = (id: string) => apiRequest<{ flashcards: Flashcard[]; warnings: { code: string; message: string }[] }>(`/api/kits/${id}/generate/flashcards`, { method: "POST" });
export const generateSchedule = (id: string) => apiRequest<{ schedule: Schedule }>(`/api/kits/${id}/generate/schedule`, { method: "POST" });
export const generateKit = (id: string) => apiRequest<{ kit: KitRecord }>(`/api/kits/${id}/generate`, { method: "POST" });
export type BuilderResponse = Pick<KitRecord, "revision" | "questions" | "questionMetadata" | "flashcards" | "flashcardMetadata" | "coverage" | "schedule" | "derivedState" | "kit" | "companyBriefMeta">;
export const updateCompanyBrief = (id: string, body: { summary?: string; what_they_do?: string; expectedRevision: number }) => apiRequest<BuilderResponse>(`/api/kits/${id}/company-brief`, { method: "PATCH", body });
export const updateQuestion = (id: string, questionId: string, body: { prompt?: string; answer_outline?: string; difficulty?: number; category?: string; requirement_ids?: string[]; expectedRevision: number }) => apiRequest<BuilderResponse>(`/api/kits/${id}/questions/${questionId}`, { method: "PATCH", body });
export const createQuestion = (id: string, body: { prompt: string; answer_outline: string; difficulty: number; category: string; requirement_ids: string[]; expectedRevision: number }) => apiRequest<BuilderResponse>(`/api/kits/${id}/questions`, { method: "POST", body });
export const deleteQuestion = (id: string, questionId: string, expectedRevision: number) => apiRequest<BuilderResponse>(`/api/kits/${id}/questions/${questionId}`, { method: "DELETE", body: { expectedRevision } });
export const reorderQuestions = (id: string, question_ids: string[], expectedRevision: number) => apiRequest<BuilderResponse>(`/api/kits/${id}/questions/reorder`, { method: "PATCH", body: { question_ids, expectedRevision } });
export const pinQuestion = (id: string, questionId: string, pinned: boolean, expectedRevision: number) => apiRequest<BuilderResponse>(`/api/kits/${id}/questions/${questionId}/pin`, { method: "PATCH", body: { pinned, expectedRevision } });
export const createFlashcard = (id: string, body: { front: string; back: string; requirement_ids: string[]; expectedRevision: number }) => apiRequest<BuilderResponse>(`/api/kits/${id}/flashcards`, { method: "POST", body });
export const updateFlashcard = (id: string, flashcardId: string, body: { front?: string; back?: string; requirement_ids?: string[]; expectedRevision: number }) => apiRequest<BuilderResponse>(`/api/kits/${id}/flashcards/${flashcardId}`, { method: "PATCH", body });
export const deleteFlashcard = (id: string, flashcardId: string, expectedRevision: number) => apiRequest<BuilderResponse>(`/api/kits/${id}/flashcards/${flashcardId}`, { method: "DELETE", body: { expectedRevision } });
export const pinFlashcard = (id: string, flashcardId: string, pinned: boolean, expectedRevision: number) => apiRequest<BuilderResponse>(`/api/kits/${id}/flashcards/${flashcardId}/pin`, { method: "PATCH", body: { pinned, expectedRevision } });
export const regenerateCompanyBrief = (id: string, expectedRevision: number) => apiRequest<BuilderResponse>(`/api/kits/${id}/regenerate/company-brief`, { method: "POST", body: { expectedRevision } });
export const regenerateQuestionCategory = (id: string, category: string, expectedRevision: number) => apiRequest<BuilderResponse>(`/api/kits/${id}/regenerate/questions/${category}`, { method: "POST", body: { expectedRevision } });
export const regenerateSchedule = (id: string, expectedRevision: number) => apiRequest<BuilderResponse>(`/api/kits/${id}/regenerate/schedule`, { method: "POST", body: { expectedRevision } });
