"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { RequireAuth } from "@/features/auth/RequireAuth";
import { KitBuilder } from "@/features/kits/KitBuilder";
import { ApiClientError } from "@/lib/api/client";
import { deleteKit, extractKit, generateKit, generateQuestions, generateSchedule, getKit, researchInterview } from "@/lib/api/kits";
import type { BuilderResponse } from "@/lib/api/kits";
import type { KitRecord } from "@/types/api";

const activeStatuses = ["queued", "crawling_company", "researching_interview", "extracting_requirements", "generating_questions", "checking_coverage", "filling_gaps", "generating_flashcards", "building_schedule", "validating"];

function DetailContent() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const [kit, setKit] = useState<KitRecord | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const kitStatus = kit?.status;
  useEffect(() => { getKit(id).then((response) => setKit(response.kit)).catch((value) => setError(value instanceof ApiClientError ? value.message : "Could not load this kit.")); }, [id]);
  useEffect(() => { if (!kitStatus || !activeStatuses.includes(kitStatus)) return undefined; const timer = window.setInterval(() => { getKit(id).then((response) => setKit(response.kit)).catch((value) => setError(value instanceof ApiClientError ? value.message : "Could not refresh generation status.")); }, 2000); return () => window.clearInterval(timer); }, [id, kitStatus]);
  if (error && !kit) return <div className="space-y-4"><p role="alert" className="text-red-700">{error}</p><Link href="/dashboard" className="underline">Back to dashboard</Link></div>;
  if (!kit) return <p className="text-sm text-slate-600">Loading kit...</p>;
  const currentKit = kit;
  const role = currentKit.extraction?.role ?? currentKit.kit?.role;
  const coverage = currentKit.coverage ?? currentKit.kit?.coverage;
  const requirements = role?.requirements ?? [];
  const active = activeStatuses.includes(kit.status);
  function applyBuilder(response: BuilderResponse) { setKit((current) => current ? { ...current, revision: response.revision, questions: response.questions, questionMetadata: response.questionMetadata, flashcards: response.flashcards, flashcardMetadata: response.flashcardMetadata, coverage: response.coverage, schedule: response.schedule, derivedState: response.derivedState, companyBriefMeta: response.companyBriefMeta, kit: response.kit } : current); setError(null); }
  async function start() { setBusy("generate"); setError(null); try { const response = await generateKit(currentKit.id); setKit(response.kit); } catch (value) { setError(value instanceof ApiClientError ? value.message : "Could not start generation."); } finally { setBusy(null); } }
  async function remove() { setBusy("delete"); try { await deleteKit(currentKit.id); router.push("/dashboard"); } catch (value) { setError(value instanceof ApiClientError ? value.message : "Could not delete this kit."); } finally { setBusy(null); } }
  async function stage(name: string, action: () => Promise<unknown>) { setBusy(name); setError(null); try { await action(); const response = await getKit(currentKit.id); setKit(response.kit); } catch (value) { setError(value instanceof ApiClientError ? value.message : `Could not run ${name}.`); } finally { setBusy(null); } }
  return <div className="space-y-8">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><Link href="/dashboard" className="text-sm text-slate-600 underline">Back to dashboard</Link><h1 className="mt-3 text-3xl font-semibold">Interview kit</h1></div><div className="flex gap-2"><button type="button" onClick={() => void start()} disabled={busy !== null || active} className="rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-60">{busy === "generate" ? "Starting..." : kit.status === "failed" ? "Retry generation" : "Generate prep kit"}</button><button type="button" onClick={() => void remove()} disabled={busy !== null || active} className="rounded-md border border-red-300 px-3 py-2 text-sm text-red-700 disabled:opacity-60">{busy === "delete" ? "Deleting..." : "Delete kit"}</button></div></div>
    {error ? <p role="alert" className="border-l-4 border-red-400 pl-3 text-sm text-red-700">{error}</p> : null}
    {active ? <section className="rounded-lg border border-blue-200 bg-blue-50 p-5"><p className="font-semibold text-blue-950">Generation in progress</p><p className="mt-1 text-sm text-blue-900">{kit.progress.message || kit.status.replaceAll("_", " ")}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-blue-100"><div className="h-full bg-blue-700 transition-all" style={{ width: `${kit.progress.percent}%` }} /></div><p className="mt-2 text-xs text-blue-800">{kit.progress.stage.replaceAll("_", " ")}</p></section> : null}
    {kit.status === "failed" ? <section className="rounded-lg border border-red-200 bg-red-50 p-5"><p className="font-semibold text-red-950">Generation stopped</p><p className="mt-1 text-sm text-red-900">{kit.generation?.error?.message || kit.progress.message}</p></section> : null}
    {kit.warnings.length ? <section className="rounded-lg border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-950">Warnings</h2><ul className="mt-2 space-y-1 text-sm text-amber-900">{kit.warnings.map((warning, index) => <li key={`${warning.code}-${index}`}>{warning.message}</li>)}</ul></section> : null}
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Status</p><p className="mt-2 font-medium capitalize">{kit.status.replaceAll("_", " ")}</p></div><div className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Company</p><p className="mt-2 break-all font-medium">{kit.input.company_url}</p></div><div className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Days available</p><p className="mt-2 font-medium">{kit.input.days}</p></div></div>
    <section className="rounded-lg border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Job description</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-700">{kit.input.jd}</p></section>
    <section className="rounded-lg border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Role analysis</h2><p className="mt-1 text-sm text-slate-600">Requirements come from the saved job description analysis.</p></div><button type="button" onClick={() => void stage("analysis", () => extractKit(currentKit.id))} disabled={busy !== null || active} className="rounded-md bg-slate-900 px-3 py-2 text-sm text-white disabled:opacity-60">{busy === "analysis" ? "Analyzing..." : "Analyze job description"}</button></div>{role ? <div className="mt-5 space-y-4"><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs uppercase tracking-wide text-slate-500">Title</p><p className="mt-1 font-medium">{role.title || "Not specified"}</p></div><div><p className="text-xs uppercase tracking-wide text-slate-500">Seniority</p><p className="mt-1 font-medium">{role.seniority || "Not specified"}</p></div><div><p className="text-xs uppercase tracking-wide text-slate-500">Location</p><p className="mt-1 font-medium">{currentKit.extraction?.role.location || "Not specified"}</p></div></div><div><h3 className="font-medium">Requirements</h3>{requirements.length ? <ul className="mt-2 space-y-2">{requirements.map((requirement) => <li key={requirement.id} className="flex flex-wrap gap-2 text-sm"><span className="font-mono text-xs text-slate-500">{requirement.id}</span><span>{requirement.text}</span><span className="rounded bg-slate-100 px-2 py-1 text-xs">{requirement.priority}</span></li>)}</ul> : <p className="mt-2 text-sm text-slate-600">No explicit requirements were found.</p>}</div></div> : <p className="mt-5 text-sm text-slate-600">No role analysis has been run yet.</p>}</section>
    <section className="rounded-lg border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Public interview research</h2><p className="mt-1 text-sm text-slate-600">Public evidence is not treated as company policy.</p></div><button type="button" onClick={() => void stage("research", () => researchInterview(kit.id))} disabled={busy !== null || active} className="rounded-md bg-slate-900 px-3 py-2 text-sm text-white disabled:opacity-60">{busy === "research" ? "Researching..." : "Research interviews"}</button></div>{kit.research?.interview ? <p className="mt-5 text-sm text-slate-700">{kit.research.interview.metadata.sourceCount} public source{kit.research.interview.metadata.sourceCount === 1 ? "" : "s"} found.</p> : <p className="mt-5 text-sm text-slate-600">No public interview research has been run yet.</p>}</section>
    <section className="rounded-lg border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Interview questions</h2><p className="mt-1 text-sm text-slate-600">Generate the initial question set before editing it.</p></div><button type="button" onClick={() => void stage("questions", () => generateQuestions(kit.id))} disabled={busy !== null || active || !role} className="rounded-md bg-slate-900 px-3 py-2 text-sm text-white disabled:opacity-60">{busy === "questions" ? "Generating..." : "Generate questions"}</button></div>{kit.questions.length ? <p className="mt-5 text-sm text-slate-700">{kit.questions.length} questions are ready for editing below.</p> : <p className="mt-5 text-sm text-slate-600">No questions have been generated yet.</p>}</section>
    <KitBuilder key={`${kit.id}-${kit.revision}`} kit={kit} onChange={applyBuilder} onError={setError} />
    <section className="rounded-lg border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Coverage</h2>{coverage ? <div className="mt-3 space-y-2 text-sm"><p>Requirements covered: {requirements.length - coverage.uncovered_requirement_ids.length} / {requirements.length}</p><p>Coverage passes: {coverage.passes}</p>{coverage.uncovered_requirement_ids.length ? <p className="text-amber-800">Uncovered: {coverage.uncovered_requirement_ids.join(", ")}</p> : <p className="text-emerald-700">All extracted requirements are covered.</p>}{kit.derivedState?.coverageStale ? <p className="text-amber-800">Coverage needs recalculation.</p> : null}</div> : <p className="mt-3 text-sm text-slate-600">Coverage appears after question generation.</p>}</section>
    <section className="rounded-lg border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Study schedule</h2><p className="mt-1 text-sm text-slate-600">Schedule allocation is deterministic and can be rebuilt after question changes.</p></div><button type="button" onClick={() => void stage("schedule", () => generateSchedule(kit.id))} disabled={busy !== null || active || !kit.questions.length} className="rounded-md bg-slate-900 px-3 py-2 text-sm text-white disabled:opacity-60">{busy === "schedule" ? "Building..." : "Rebuild schedule"}</button></div>{kit.schedule ? <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{kit.schedule.days.map((day) => <article key={day.day} className="rounded-md border border-slate-200 p-4"><div className="flex justify-between"><h3 className="font-medium">Day {day.day}</h3><span className="text-sm text-slate-500">{day.minutes} min</span></div><p className="mt-2 text-sm">{day.focus}</p><p className="mt-3 text-xs text-slate-500">Questions: {day.question_ids.join(", ") || "Review only"}</p></article>)}</div> : <p className="mt-5 text-sm text-slate-600">No schedule has been built yet.</p>}{kit.derivedState?.scheduleStale ? <p className="mt-4 text-sm text-amber-800">This schedule is stale because question changes affected must-have coverage. Rebuild it when ready.</p> : null}</section>
  </div>;
}

export default function KitDetailPage() { return <RequireAuth><DetailContent /></RequireAuth>; }
