"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { RequireAuth } from "@/features/auth/RequireAuth";
import { ApiClientError } from "@/lib/api/client";
import { deleteKit, extractKit, generateFlashcards, generateKit, generateQuestions, generateSchedule, getKit, researchInterview } from "@/lib/api/kits";
import type { KitRecord } from "@/types/api";

function DetailContent() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const [kit, setKit] = useState<KitRecord | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<"generate" | "extract" | "research" | "questions" | "flashcards" | "schedule" | "delete" | null>(null);

  useEffect(() => {
    getKit(id).then((response) => setKit(response.kit)).catch((value) => setError(value instanceof ApiClientError ? value.message : "Could not load this kit."));
  }, [id]);

  useEffect(() => {
    const active = kit?.status === "queued" || kit?.status === "crawling_company" || kit?.status === "researching_interview" || kit?.status === "extracting_requirements" || kit?.status === "generating_questions" || kit?.status === "checking_coverage" || kit?.status === "filling_gaps" || kit?.status === "generating_flashcards" || kit?.status === "building_schedule" || kit?.status === "validating";
    if (!active) return undefined;
    const timer = window.setInterval(() => { getKit(id).then((response) => setKit(response.kit)).catch((value) => setError(value instanceof ApiClientError ? value.message : "Could not refresh generation status.")); }, 2000);
    return () => window.clearInterval(timer);
  }, [id, kit?.status]);

  if (error) return <div className="space-y-4"><p role="alert" className="text-red-700">{error}</p><Link href="/dashboard" className="underline">Back to dashboard</Link></div>;
  if (!kit) return <p className="text-sm text-slate-600">Loading kit...</p>;

  const kitId = kit.id;
  async function startGeneration() { setBusy("generate"); setError(null); try { const response = await generateKit(kitId); setKit(response.kit); } catch (value) { setError(value instanceof ApiClientError ? value.message : "Could not start prep kit generation."); } finally { setBusy(null); } }
  async function remove() { setBusy("delete"); try { await deleteKit(kitId); router.push("/dashboard"); } catch (value) { setError(value instanceof ApiClientError ? value.message : "Could not delete this kit."); } finally { setBusy(null); } }
  async function analyze() { setBusy("extract"); setError(null); try { const response = await extractKit(kitId); setKit((current) => current ? { ...current, extraction: response.extraction, status: "extracting_requirements" } : current); } catch (value) { setError(value instanceof ApiClientError ? value.message : "Could not analyze this job description."); } finally { setBusy(null); } }
  async function research() { setBusy("research"); setError(null); try { const response = await researchInterview(kitId); setKit((current) => current ? { ...current, research: { ...(current.research ?? {}), interview: response.research } } : current); } catch (value) { setError(value instanceof ApiClientError ? value.message : "Could not run interview research."); } finally { setBusy(null); } }
  async function generate() { setBusy("questions"); setError(null); try { const response = await generateQuestions(kitId); setKit((current) => current ? { ...current, questions: response.questions, coverage: response.coverage, status: "completed" } : current); } catch (value) { setError(value instanceof ApiClientError ? value.message : "Could not generate interview questions."); } finally { setBusy(null); } }
  async function makeFlashcards() { setBusy("flashcards"); setError(null); try { const response = await generateFlashcards(kitId); setKit((current) => current ? { ...current, flashcards: response.flashcards, status: "generating_flashcards" } : current); } catch (value) { setError(value instanceof ApiClientError ? value.message : "Could not generate flashcards."); } finally { setBusy(null); } }
  async function makeSchedule() { setBusy("schedule"); setError(null); try { const response = await generateSchedule(kitId); setKit((current) => current ? { ...current, schedule: response.schedule, status: "building_schedule" } : current); } catch (value) { setError(value instanceof ApiClientError ? value.message : "Could not build the study schedule."); } finally { setBusy(null); } }

  const role = kit.extraction?.role;
  const interview = kit.research?.interview;
  const coverage = kit.coverage;
  const requirements = role?.requirements ?? [];
  const coveredCount = coverage ? requirements.length - coverage.uncovered_requirement_ids.length : 0;
  const disabled = busy !== null;
  const generationActive = kit.status === "queued" || ["crawling_company", "researching_interview", "extracting_requirements", "generating_questions", "checking_coverage", "filling_gaps", "generating_flashcards", "building_schedule", "validating"].includes(kit.status);
  return <div className="space-y-8">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><Link href="/dashboard" className="text-sm text-slate-600 underline">Back to dashboard</Link><h1 className="mt-3 text-3xl font-semibold">Interview kit</h1></div><div className="flex gap-2"><button type="button" onClick={startGeneration} disabled={disabled || generationActive} className="rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-60">{busy === "generate" ? "Starting..." : kit.status === "failed" ? "Retry generation" : "Generate prep kit"}</button><button type="button" onClick={remove} disabled={disabled || generationActive} className="rounded-md border border-red-300 px-3 py-2 text-sm text-red-700 disabled:opacity-60">{busy === "delete" ? "Deleting..." : "Delete kit"}</button></div></div>
    {error ? <p role="alert" className="border-l-4 border-red-400 pl-3 text-sm text-red-700">{error}</p> : null}
    {kit.status !== "completed" && kit.status !== "completed_with_warnings" && kit.status !== "queued" ? <section className="rounded-lg border border-blue-200 bg-blue-50 p-5"><p className="text-sm font-semibold text-blue-950">Generating your prep kit</p><p className="mt-1 text-sm text-blue-900">{kit.progress.message || kit.status.replaceAll("_", " ")}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-blue-100"><div className="h-full bg-blue-700 transition-all" style={{ width: `${kit.progress.percent}%` }} /></div><p className="mt-2 text-xs text-blue-800">Current stage: {kit.progress.stage.replaceAll("_", " ")}</p></section> : null}
    {kit.status === "queued" ? <section className="rounded-lg border border-blue-200 bg-blue-50 p-5"><p className="text-sm font-semibold text-blue-950">Generation queued</p><p className="mt-1 text-sm text-blue-900">The backend will begin the staged prep flow shortly.</p></section> : null}
    {kit.status === "failed" ? <section className="rounded-lg border border-red-200 bg-red-50 p-5"><p className="text-sm font-semibold text-red-950">Generation stopped</p><p className="mt-1 text-sm text-red-900">{kit.generation?.error?.message || kit.progress.message || "The prep kit could not be completed."}</p></section> : null}
    {kit.warnings.length ? <section className="rounded-lg border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-950">Generation warnings</h2><ul className="mt-2 space-y-1 text-sm text-amber-900">{kit.warnings.map((warning, index) => <li key={`${warning.code}-${index}`}>{warning.message}</li>)}</ul></section> : null}
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Status</p><p className="mt-2 font-medium capitalize">{kit.status.replaceAll("_", " ")}</p></div><div className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Company</p><p className="mt-2 break-all font-medium">{kit.input.company_url}</p></div><div className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Days available</p><p className="mt-2 font-medium">{kit.input.days}</p></div></div>
    <section className="rounded-lg border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Job description</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-700">{kit.input.jd}</p></section>
    <section className="rounded-lg border border-slate-200 bg-white p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-semibold">Role analysis</h2><p className="mt-1 text-sm text-slate-600">Requirements come from the pasted job description only.</p></div><button type="button" onClick={analyze} disabled={disabled} className="rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-60">{busy === "extract" ? "Analyzing..." : "Analyze job description"}</button></div>{role ? <div className="mt-5 space-y-5"><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs uppercase tracking-wide text-slate-500">Title</p><p className="mt-1 font-medium">{role.title || "Not specified"}</p></div><div><p className="text-xs uppercase tracking-wide text-slate-500">Seniority</p><p className="mt-1 font-medium">{role.seniority || "Not specified"}</p></div><div><p className="text-xs uppercase tracking-wide text-slate-500">Location</p><p className="mt-1 font-medium">{role.location || "Not specified"}</p></div></div>{role.responsibilities.length ? <div><h3 className="font-medium">Responsibilities</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-700">{role.responsibilities.map((item) => <li key={item}>{item}</li>)}</ul></div> : null}<div><h3 className="font-medium">Requirements</h3>{role.requirements.length ? <ul className="mt-2 space-y-2">{role.requirements.map((requirement) => <li key={requirement.id} className="flex flex-wrap items-center gap-2 text-sm"><span className="font-mono text-xs text-slate-500">{requirement.id}</span><span>{requirement.text}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs capitalize">{requirement.kind}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{requirement.priority}</span></li>)}</ul> : <p className="mt-2 text-sm text-slate-600">No explicit requirements were found.</p>}</div></div> : <p className="mt-5 text-sm text-slate-600">No role analysis has been run for this kit yet.</p>}</section>
    <section className="rounded-lg border border-slate-200 bg-white p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-semibold">Public interview research</h2><p className="mt-1 text-sm text-slate-600">Public evidence is not treated as company policy.</p></div><button type="button" onClick={research} disabled={disabled} className="rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-60">{busy === "research" ? "Researching..." : "Research interviews"}</button></div>{interview ? <div className="mt-5 space-y-4"><p className="text-sm text-slate-700">{interview.metadata.sourceCount} source{interview.metadata.sourceCount === 1 ? "" : "s"} found.</p>{interview.sources.length ? <ul className="space-y-2">{interview.sources.map((source) => <li key={source.sourceId}><a href={source.url} target="_blank" rel="noopener noreferrer" className="font-medium text-slate-900 underline">{source.title}</a><span className="ml-2 text-xs text-slate-500">{source.domain} · {source.authority}</span></li>)}</ul> : <p className="text-sm text-slate-600">No public interview discussion was found.</p>}</div> : <p className="mt-5 text-sm text-slate-600">No public interview research has been run for this kit yet.</p>}</section>
    <section className="rounded-lg border border-slate-200 bg-white p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-semibold">Interview questions</h2><p className="mt-1 text-sm text-slate-600">Questions are grounded in the saved role analysis.</p></div><button type="button" onClick={generate} disabled={disabled || !role} className="rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-60">{busy === "questions" ? "Generating..." : "Generate interview questions"}</button></div>{kit.questions.length ? <div className="mt-5 space-y-6">{kit.questions.map((question) => <article key={question.id} className="rounded-md border border-slate-200 p-4"><div className="flex flex-wrap items-center gap-2 text-xs text-slate-500"><span className="font-mono">{question.id}</span><span>Difficulty {question.difficulty}</span><span>Covers: {question.requirement_ids.join(", ") || "none"}</span></div><h3 className="mt-2 font-medium">{question.prompt}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{question.answer_outline}</p></article>)}</div> : <p className="mt-5 text-sm text-slate-600">Analyze the job description first, then generate questions.</p>}</section>
    <section className="rounded-lg border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Coverage</h2>{requirements.length === 0 ? <p className="mt-3 text-sm text-slate-600">No explicit JD requirements were extracted.</p> : coverage ? <div className="mt-3 space-y-3 text-sm"><p>Requirements covered: {coveredCount} / {requirements.length}</p><p>Passes: {coverage.passes}</p>{coverage.uncovered_requirement_ids.length ? <div><p className="font-medium text-amber-800">Uncovered requirements</p><ul className="mt-1 space-y-1 text-amber-800">{coverage.uncovered_requirement_ids.map((requirementId) => { const requirement = requirements.find((item) => item.id === requirementId); return <li key={requirementId}>{requirementId} - {requirement?.priority ?? "unknown"}{requirement ? `: ${requirement.text}` : ""}</li>; })}</ul></div> : <p className="text-emerald-700">All extracted requirements are covered.</p>}</div> : <p className="mt-3 text-sm text-slate-600">Coverage will appear after questions are generated.</p>}</section>
    <section className="rounded-lg border border-slate-200 bg-white p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-semibold">Flashcards</h2><p className="mt-1 text-sm text-slate-600">Concise rehearsal cues grounded in the role and questions.</p></div><button type="button" onClick={makeFlashcards} disabled={disabled || !role || !kit.questions.length} className="rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-60">{busy === "flashcards" ? "Generating..." : "Generate flashcards"}</button></div>{kit.flashcards.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{kit.flashcards.map((card) => <article key={card.id} className="rounded-md border border-slate-200 p-4"><p className="font-medium">{card.front}</p><p className="mt-3 text-sm leading-6 text-slate-600">{card.back}</p><p className="mt-3 text-xs text-slate-500">Requirements: {card.requirement_ids.join(", ") || "general role context"}</p></article>)}</div> : <p className="mt-5 text-sm text-slate-600">Generate questions before creating flashcards.</p>}</section>
    <section className="rounded-lg border border-slate-200 bg-white p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-semibold">Study schedule</h2><p className="mt-1 text-sm text-slate-600">Minutes and day allocation are calculated deterministically.</p></div><button type="button" onClick={makeSchedule} disabled={disabled || !role || !kit.questions.length} className="rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-60">{busy === "schedule" ? "Building..." : "Build study schedule"}</button></div>{kit.schedule ? <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{kit.schedule.days.map((day) => <article key={day.day} className="rounded-md border border-slate-200 p-4"><div className="flex items-center justify-between"><h3 className="font-medium">Day {day.day}</h3><span className="text-sm text-slate-500">{day.minutes} min</span></div><p className="mt-2 text-sm text-slate-700">{day.focus}</p><p className="mt-3 text-xs text-slate-500">Questions: {day.question_ids.join(", ") || "Review only"}</p></article>)}</div> : <p className="mt-5 text-sm text-slate-600">Generate questions before building a schedule.</p>}</section>
  </div>;
}

export default function KitDetailPage() { return <RequireAuth><DetailContent /></RequireAuth>; }
